micronaut:
  application:
    name: observerInsight
  server:
    port: ${APPLICATION_SERVER_PORT:8080}

source:
  type: MONGO
  database: reports

mongodb:
  uri: mongodb://root:password@localhost:27017



