micronaut:
  application:
    name: observer-insight
  server:
    port: ${APPLICATION_SERVER_PORT:8080}

source:
  type: ${SOURCE_TYPE:MONGO}
  database: ${DATABASE_NAME:reports}

mongodb:
  uri: mongodb://${MONGO_USERNAME:root}:${MONGO_PASSWORD:password}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}



